@TaskNetic_HostAddress = http://localhost:5200



POST {{TaskNetic_HostAddress}}/api/comments/card/0
Content-Type: application/json

{
  NewCommentRequest: {
    Comment: "This is a comment",
    UserId: "80f94f82-a6fd-48dc-ba7e-1d5367439b17"
  }
}

###
